### ISSUE TITLE
imgLazyLoadComponent.html:2 ERROR TypeError: Object(...) is not a function     at thisissoon-angular-inviewport.js:266

### ISSUE THREAD

**Issue by zxjQAZ** [thisissoon/angular-inviewport#24]
i used as docuemnt, but the error hanppened,  is it because My angualr version is 5

**Comment by edoparearyee** [comment]
Hi @zxjQAZ if your using angular 5 I would suggest using v2.2.0 of this library.

Closing this for now however if this is still an issue feel free to reopen it.
