### ISSUE TITLE
Best way to either test interaction within a specific region

### ISSUE THREAD

**Issue by mcblum** [thisissoon/angular-inviewport#29]
So our app is a series of forms, and each question should activate when it hits a certain region, think a 200px horizontal stripe across a web page. I've made that a fixed-pos div, but that doesn't seem to work. What would be the best way to test interaction within a specific range of the viewport?

Thank you for your work on this!

**Comment by edoparearyee** [comment]
You can set offsets using the [Intersection Observer API](https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API) options and passing it to the directive like [here](https://github.com/thisissoon/angular-inviewport#offset-example) to target a certain region of the viewport
