### ISSUE TITLE
getting error when using debounce time

### ISSUE THREAD

**Issue by SimranChawla1995** [thisissoon/angular-inviewport#35]
This is the error i get -
Type 'Observable<boolean>' is not assignable to type 'Subject<boolean>'.
  Property 'observers' is missing in type 'Observable<boolean>'.

What i want is to delay the first call to event till view initializes. Please throw some light on the issue.

**Comment by jamesjwarren** [comment]
The debounce example needs updating, pipe returns an `Observable` not a `Subject` so the result can't be assigned to `inViewportChange`. This should get you going:
```ts
import { Subject } from 'rxjs';
import { debounceTime } from 'rxjs/operators';

export class AppComponent {
  inViewportChange = new Subject<boolean>();

  constructor() {
    this.inViewportChange
      .pipe(debounceTime(300))
      .subscribe((inViewport: boolean) =>
        console.log(`element is in viewport: ${inViewport}`)
      );
  }

  onInViewportChange(inViewport: boolean) {
    this.inViewportChange.next(inViewport);
  }
}
```

**Comment by SimranChawla1995** [comment]
Thanks !!!

**Comment by SimranChawla1995** [comment]
Actually sir, I'm getting this warning -
ng2-facebook-sdk: tried calling instance method before component is ready.
So, I want to defer the first event binding only after component is ready. Can you please help to resolve this.

**Comment by jamesjwarren** [comment]
Unfortunately that is likely an error specific to your usage and I can't tell what is causing that without more context. I would try using the `snInViewport` on a wrapping element rather than directly on another component if that causes issues. You could also move the `inViewportChange` subscription into one of Angular's lifecycle hooks for greater control.

**Comment by SimranChawla1995** [comment]
Let me explain..
This is my html -
`  <fb-video #fbPlayer snInViewport (inViewportChange)="onInViewportChange($event)" 
  *ngIf="post.postType == 'PostTypeVideoFacebook'" [href]="post.postLink"></fb-video>`

This is my component file
`      onInViewportChange(inViewport: boolean) {
        this.inViewportChange.next(inViewport);
      }

      ngAfterViewInit() {
        this.inViewportChange
        .pipe(debounceTime(1000))
        .subscribe((inViewport: boolean) =>
        {
          if(inViewport == false){
          this.fbplayer.pause();
           console.log(`element is in viewport: ${inViewport}`)
        }}
        );`

I'm using ngx-facebook npm to import FacebookComponent . It would be great if you could suggest how can i resolve this.

**Comment by jamesjwarren** [comment]
We are unable to offer support for your specific integration with another third party library, if you managed to find a fix/solution for your use-case feel free to post the details here.
