### ISSUE TITLE
Add ability to set offset for when element is in viewport

### ISSUE THREAD

**Issue by edoparearyee** [thisissoon/angular-inviewport#4]
Example:

```html
<p inViewport [offset.top]="100" [offset.bottom]="-100">very large element</p>
```

Where `100` means the element has to be `100px` inside the viewport until the event is triggered and `-100` means the element can be `100px` outside the viewport and the event will be triggered.

**Comment by GrahamHotchkiss** [comment]
This is a deal-breaker for me - fixed headers make this unusable. Otherwise this is a great, no-fuss, module
