### ISSUE TITLE
Doesnt work with angular 10

### ISSUE THREAD

**Issue by DanielFuchs98** [thisissoon/angular-inviewport#41]
When i´m updating to angular 10, i get following error message:

                 Package "@thisissoon/`angular-inviewport" has an incompatible peer dependency to "@angular/core" (requires ">=5.0.0 <9.0.0" (extended), would install "10.0.0").`

Please increase the peer depencency to version 10.

**Comment by rodrigosanchezg8** [comment]
Yes, i had to drop this dependency for Angular 10. Please update to it.

**Comment by jamesjwarren** [comment]
Thanks for the issue report, there may well be other issues when upgrading the package to work with the latest Angular version (see #42). Unfortunately we're not actively maintaining this package but we would happily welcome MRs to support the latest version of Angular.
