### ISSUE TITLE
Manually force the directive to recalculate inViewport status.

### ISSUE THREAD

**Issue by paulordbm** [thisissoon/angular-inviewport#9]
Hi again, @edoparearyee!

Is there currently a way to manually force the directive to recalculate it's `inViewport` status?

I have a page of arbitrary content size between a header and a footer. I use this directive to know if the footer is inside the viewport or not, so the footer is inside a parent, scrollable div. 

At startup both the header and the footer are visible, then I fetch content data from the server, which might push the footer outside of the view.

What I noticed is that my footer's `inViewport` state is never updated during this process unless I hack my way out with a call to `window.dispatchEvent(new Event('resize'))` inside my component's `ngOnInit()`.

Is there any way around this?

If you want to, I could contribute this new feature with your guidance (never contributed to OSS before).

Thanks again!

**Comment by edoparearyee** [comment]
@paulordbm at the moment theres no way to manually recalculate a `inViewport` check. I think dispatching a `resize` or `scroll` event is a good work around for now.

Maybe it's possible to grab the directive instance by setting the `exportAs` value in the directive metadata:


```ts
@Directive({
  selector: '[inViewport], [snInViewport]',
  exportAs: 'snInViewport'
})
```

then in your template simply bind the directive to a variable:

```html
<div snInViewport #myDiv="snInViewport"></div>
```

Then in the `component.ts` file declare that variable in the class

```ts
@ViewChild('myDiv') myDiv: InViewportDirective

myFunc() {
  myDiv.calculateInViewportStatus();
}
```

If you want to  have a go at making a pull request, please feel free to do so.
